# https://taskfile.dev

version: '3'

tasks:
  default:
    silent: true
    cmds:
      - cmd: task --list-all
        platforms: [linux]
      - cmd: task.exe --list-all
        platforms: [windows]

  clean:
    cmds:
      - cmd: rm -rf build
        platforms: [linux]
      - cmd: rm -rf conan
        platforms: [linux]
      - cmd: rmdir /s /q build
        platforms: [windows]
      - cmd: rmdir /s /q conan
        platforms: [windows]

  config_win:
    internal: true
    platforms: [windows]
    cmds:
      - conan install . --output-folder=conan --build=missing -s build_type=Release --profile:build=profiles/gcc12_x64 --profile:host=profiles/gcc12_x64
      - cmake -DCMAKE_TOOLCHAIN_FILE=conan_toolchain -DCMAKE_BUILD_TYPE=Release -S . -B build
    sources:
      - CMakeLists.txt
      - src/**/CMakeLists.txt
      - include/**/CMakeLists.txt
      - tests/**/CMakeLists.txt
      - external/**/CMakeLists.txt
      - cmake/**/CMakeLists.txt
    generates:
      - build/compile_commands.json

  config_linux:
    internal: true
    platforms: [linux]
    cmds:
      - conan install . --output-folder=conan --build=missing -s build_type=Release --profile:build=profiles/gcc12_x64 --profile:host=profiles/gcc12_x64
      - cmake -DCMAKE_TOOLCHAIN_FILE=conan_toolchain -DCMAKE_BUILD_TYPE=Release -S . -B build
    sources:
      - CMakeLists.txt
      - src/**/CMakeLists.txt
      - include/**/CMakeLists.txt
      - tests/**/CMakeLists.txt
      - external/**/CMakeLists.txt
      - cmake/**/CMakeLists.txt
    generates:
      - build/compile_commands.json

  config_win_debug:
    internal: true
    platforms: [windows]
    cmds:
      - conan install . --output-folder=conan --build=missing -s build_type=Debug --profile:build=profiles/gcc12_x64 --profile:host=profiles/gcc12_x64
      - cmake -DCMAKE_TOOLCHAIN_FILE=conan_toolchain -DCMAKE_BUILD_TYPE=Debug -S . -B build
    sources:
      - CMakeLists.txt
      - src/**/CMakeLists.txt
      - include/**/CMakeLists.txt
      - tests/**/CMakeLists.txt
      - external/**/CMakeLists.txt
      - cmake/**/CMakeLists.txt
    generates:
      - build/compile_commands.json

  config_linux_debug:
    internal: true
    platforms: [linux]
    cmds:
      - conan install . --output-folder=conan --build=missing -s build_type=Debug --profile:build=profiles/gcc12_x64 --profile:host=profiles/gcc12_x64
      - cmake -DCMAKE_TOOLCHAIN_FILE=conan_toolchain -DCMAKE_BUILD_TYPE=Debug -S . -B build
    sources:
      - CMakeLists.txt
      - src/**/CMakeLists.txt
      - include/**/CMakeLists.txt
      - tests/**/CMakeLists.txt
      - external/**/CMakeLists.txt
      - cmake/**/CMakeLists.txt
    generates:
      - build/compile_commands.json

  config_debug:
    cmds:
      - task: config_linux_debug
      - task: config_win_debug

  config:
    cmds:
      - task: config_linux
      - task: config_win

  build_debug:
    cmds:
      - task: config_debug
      - cmd: cmake --build build
        platforms: [linux]
      - cmd: cmake --build build --config Debug --target ALL_BUILD
        platforms: [windows]

  build:
    cmds:
      - task: config
      - cmd: cmake --build build
        platforms: [linux]
      - cmd: cmake --build build --config Release --target ALL_BUILD
        platforms: [windows]

  pack:
    cmds:
      - cmd: cd build && cpack -B install -C Release

  test:
    cmds:
      - cmd: ctest --test-dir build/tests --output-on-failure

  run:
    cmds:
      - cmd: build/src/my_project
